Repository fossasia/open-event-organizer-android, pull requests merged in 2018-03, with the labels that each got.

#664 feat: Added FAQ List for an Event
  app/src/main/java/org/fossasia/openevent/app/common/app/di/component/AppComponent.java
  app/src/main/java/org/fossasia/openevent/app/common/app/di/module/DataModule.java
  app/src/main/java/org/fossasia/openevent/app/common/app/di/module/NetworkModule.java
  app/src/main/java/org/fossasia/openevent/app/common/app/di/module/PresenterModule.java
  app/src/main/java/org/fossasia/openevent/app/common/data/models/Event.java
  app/src/main/java/org/fossasia/openevent/app/common/data/models/Faq.java
  app/src/main/java/org/fossasia/openevent/app/common/data/models/delegates/EventDelegate.java
  app/src/main/java/org/fossasia/openevent/app/common/data/models/delegates/contract/IEventDelegate.java
  app/src/main/java/org/fossasia/openevent/app/common/data/network/EventService.java
  app/src/main/java/org/fossasia/openevent/app/common/data/repository/FaqRepository.java
  app/src/main/java/org/fossasia/openevent/app/common/data/repository/contract/IFAQRepository.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListAdapter.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListPresenter.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/list/contract/IFaqListPresenter.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/list/contract/IFaqListView.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/list/viewholder/FaqViewHolder.java
  app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
  app/src/main/res/drawable/ic_faq.xml
  app/src/main/res/layout/faq_layout.xml
  app/src/main/res/layout/faqs_fragment.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: resolved

#651 Fixed showing unknown info from UI issue #628
  app/src/main/res/layout/about_event_detail.xml
  app/src/main/res/layout/bottomsheet_attendee_check_in.xml
  app/src/main/res/layout/organizer_detail_layout.xml
Labels: has-PR, invalid

#687 feature: Implement local timezone selection by default while creating…
  app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventPresenter.java
  app/src/main/java/org/fossasia/openevent/app/module/event/create/contract/ICreateEventView.java
Labels: invalid

#674 chore: Update dependencies
  .travis.yml
  app/build.gradle
  app/config.gradle
Labels: needs-review

#833 Revert "About#751"
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventActivity.java
  app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/about/contract/IAboutEventVew.java
  app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
  app/src/main/res/layout/about_event_activity.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/test/java/org/fossasia/openevent/app/robo/ui/ActivityInstanceTest.java
Labels: needs-review

#834 fix: Remove loader based presenter injection
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseActivity.java
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseBottomSheetFragment.java
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseFragment.java
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/LoaderHandler.java
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/loader/IPresenterProvider.java
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/loader/PresenterLoader.java
  app/src/main/java/org/fossasia/openevent/app/module/attendee/checkin/AttendeeCheckInFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/attendee/list/AttendeesFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/attendee/qrscan/ScanQRActivity.java
  app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/request/ForgotPasswordFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/auth/forgot/password/token/submit/ResetPasswordByTokenFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/auth/login/LoginFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/auth/signup/SignUpFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/chart/ChartActivity.java
  app/src/main/java/org/fossasia/openevent/app/module/event/copyright/CreateCopyrightFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/copyright/update/UpdateCopyrightFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/dashboard/EventDashboardFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/list/EventListFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/create/CreateFaqFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/faq/list/FaqListFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/main/MainActivity.java
  app/src/main/java/org/fossasia/openevent/app/module/organizer/detail/OrganizerDetailFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/organizer/password/ChangePasswordFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/ticket/create/CreateTicketFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/ticket/detail/TicketDetailFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/ticket/list/TicketsFragment.java
Labels: needs-review

#838 fix: Detach presenters onStop
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseActivity.java
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseBottomSheetFragment.java
  app/src/main/java/org/fossasia/openevent/app/common/app/lifecycle/view/BaseFragment.java
Labels: needs-review

#842 fix: Set color of overflow dynamically
  app/src/main/java/org/fossasia/openevent/app/module/event/about/AboutEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/about/ToolbarColorChanger.java
Labels: needs-review

#755 Add Place Picker widget for the 'Create Event Form' #706
  app/build.gradle
  app/config.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/module/event/create/CreateEventPresenter.java
  app/src/main/java/org/fossasia/openevent/app/module/event/create/contract/ICreateEventPresenter.java
  app/src/main/res/layout/event_create_form.xml
  app/src/main/res/values/strings.xml
Labels: DO-NOT-MERGE

#850 feat: Add Dagger Android support
  app/build.gradle
  app/config.gradle
  app/proguard-rules.pro
  app/src/main/java/org/fossasia/openevent/app/OrgaApplication.java
  app/src/main/java/org/fossasia/openevent/app/common/di/AppInjector.java
  app/src/main/java/org/fossasia/openevent/app/common/di/Injectable.java
  app/src/main/java/org/fossasia/openevent/app/common/di/component/AppComponent.java
  app/src/main/java/org/fossasia/openevent/app/common/di/component/BarcodeComponent.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/AppModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/BarcodeModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/DatabaseModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/ModelModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/NetworkModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/RepoModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/android/AboutFragmentBuildersModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/android/ActivityBuildersModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/android/AuthFragmentBuildersModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/android/BarcodeActivityBuildersModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/android/MainFragmentBuildersModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/android/OrganizerFragmentBuildersModule.java
  app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseBottomSheetFragment.java
  app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseFragment.java
  app/src/main/java/org/fossasia/openevent/app/common/mvp/view/BaseInjectActivity.java
  app/src/main/java/org/fossasia/openevent/app/core/attendee/checkin/AttendeeCheckInFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/attendee/checkin/job/AttendeeCheckInJob.java
  app/src/main/java/org/fossasia/openevent/app/core/attendee/list/AttendeesFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/attendee/qrscan/ScanQRActivity.java
  app/src/main/java/org/fossasia/openevent/app/core/auth/AuthActivity.java
  app/src/main/java/org/fossasia/openevent/app/core/auth/forgot/request/ForgotPasswordFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/auth/forgot/submit/ResetPasswordByTokenFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/auth/login/LoginFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/auth/signup/SignUpFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventActivity.java
  app/src/main/java/org/fossasia/openevent/app/core/event/about/AboutEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/event/chart/ChartActivity.java
  app/src/main/java/org/fossasia/openevent/app/core/event/copyright/CreateCopyrightFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/event/copyright/update/UpdateCopyrightFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/event/create/CreateEventFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/event/dashboard/EventDashboardFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/event/list/EventListFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/faq/create/CreateFaqFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/faq/list/FaqListFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/main/MainActivity.java
  app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailActivity.java
  app/src/main/java/org/fossasia/openevent/app/core/organizer/detail/OrganizerDetailFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/organizer/password/ChangePasswordFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/ticket/create/CreateTicketFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/ticket/detail/TicketDetailFragment.java
  app/src/main/java/org/fossasia/openevent/app/core/ticket/list/TicketsFragment.java
Labels: needs-review

#854 feat: Prepare for MVVM migration
  app/build.gradle
  app/config.gradle
  app/src/main/java/org/fossasia/openevent/app/common/di/OrgaViewModelFactory.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/AppModule.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelKey.java
  app/src/main/java/org/fossasia/openevent/app/common/di/module/ViewModelModule.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  versions.gradle
Labels: needs-review

#856 fix: APK upload on build
  scripts/update-apk.sh
Labels: needs-review

#857 Circle CI
  .circleci/config.yml
  .travis.yml
  app/build.gradle
Labels: needs-review
