Repository fossasia/open-event-organizer-android, pull requests merged in 2019-05, with the labels that each got.

#1627 chore: Bump version code and name
  app/build.gradle
Labels: chore

#1625 chore: Release v1.1.1
  README.md
  app/build.gradle
  app/jacoco.gradle
  app/src/main/java/com/eventyay/organizer/data/event/EventStatistics.java
  app/src/main/java/com/eventyay/organizer/data/event/SpeakerStatistics.java
  app/src/main/res/layout/bottomsheet_attendee_check_in.xml
  app/src/main/res/layout/event_statistics.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  versions.gradle
Labels: chore

#1639 fix: Prevent closing of Edit Event without confirmation dialog
  app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventActivity.java
Labels: fix

#1642 chore: Convert SalesSummaryPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/event/list/sales/SalesSummaryFragment.java
  app/src/main/java/com/eventyay/organizer/core/event/list/sales/SalesSummaryPresenter.java
  app/src/main/java/com/eventyay/organizer/core/event/list/sales/SalesSummaryViewModel.java
Labels: chore

#1637 feat: Pagination in Attendees list
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesPresenter.java
  app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeApi.java
  app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeRepository.java
  app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeRepositoryImpl.java
  app/src/test/java/com/eventyay/organizer/core/presenter/AttendeePresenterTest.java
Labels: feature

#1647 fix: Prevent crash at check-in on second page onwards
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesPresenter.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/SwipeController.java
Labels: fix

#1644 chore: Add unit tests for SalesSummaryViewModel
  app/src/test/java/com/eventyay/organizer/core/event/sales/SalesSummaryViewModelTest.java
Labels: chore

#1649 chore: Update LeakCanary
  app/build.gradle
  app/src/main/java/com/eventyay/organizer/OrgaApplication.java
  app/src/main/java/com/eventyay/organizer/common/mvp/view/BaseBottomSheetFragment.java
  app/src/main/java/com/eventyay/organizer/common/mvp/view/BaseDialogFragment.java
  app/src/main/java/com/eventyay/organizer/common/mvp/view/BaseFragment.java
  versions.gradle
Labels: chore

#1651 fix: Refresh sponsors list automatically on deletion of items
  app/src/main/java/com/eventyay/organizer/core/sponsor/list/SponsorsPresenter.java
Labels: fix

#1652 fix: Update sponsors list automatically on creation of new item
  app/src/main/java/com/eventyay/organizer/core/sponsor/list/SponsorsFragment.java
  app/src/main/java/com/eventyay/organizer/core/sponsor/list/SponsorsPresenter.java
Labels: fix

#1657 chore: Migrate FeedbackListPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListAdapter.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListFragment.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListPresenter.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListViewModel.java
  app/src/test/java/com/eventyay/organizer/core/feedback/FeedbackListViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/presenter/FeedbackListPresenterTest.java
Labels: chore

#1659 chore: Migrate FaqListPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListAdapter.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListViewModel.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/viewholder/FaqViewHolder.java
  app/src/main/res/layout/faq_layout.xml
  app/src/test/java/com/eventyay/organizer/core/faq/list/FaqListViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/presenter/FaqListPresenterTest.java
Labels: chore

#1666 chore: Merge development into room
  app/build.gradle
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListAdapter.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListViewModel.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/viewholder/FaqViewHolder.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListAdapter.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListFragment.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListPresenter.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListViewModel.java
  app/src/main/res/layout/faq_layout.xml
  app/src/test/java/com/eventyay/organizer/core/faq/list/FaqListViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/feedback/FeedbackListViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/presenter/FaqListPresenterTest.java
  app/src/test/java/com/eventyay/organizer/core/presenter/FeedbackListPresenterTest.java
Labels: chore

#1654 chore: Migrate FAQ module to Room database
  app/build.gradle
  app/src/main/java/com/eventyay/organizer/common/di/AppInjector.java
  app/src/main/java/com/eventyay/organizer/common/di/module/AppModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/DatabaseModule.java
  app/src/main/java/com/eventyay/organizer/core/faq/create/CreateFaqViewModel.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListViewModel.java
  app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeCheckInWork.java
  app/src/main/java/com/eventyay/organizer/data/db/configuration/EventIdConverter.java
  app/src/main/java/com/eventyay/organizer/data/db/configuration/OrgaRoomDatabase.java
  app/src/main/java/com/eventyay/organizer/data/faq/Faq.java
  app/src/main/java/com/eventyay/organizer/data/faq/FaqDao.java
  app/src/main/java/com/eventyay/organizer/data/faq/FaqRepository.java
  app/src/main/java/com/eventyay/organizer/data/faq/FaqRepositoryImpl.java
  app/src/test/java/com/eventyay/organizer/core/faq/create/CreateFaqViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/faq/list/FaqListViewModelTest.java
  app/src/test/java/com/eventyay/organizer/data/repository/FaqRepositoryTest.java
  versions.gradle
Labels: chore

#1675 fix: Prevent crash on refreshing Event Dashboard
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/analyser/ChartAnalyser.java
  versions.gradle
Labels: fix

#1673 fix: Update check-in system to work properly
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesPresenter.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesView.java
  app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeRepositoryImpl.java
Labels: fix
