Repository fossasia/open-event-organizer-android, pull requests merged in 2019-04, with the labels that each got.

#1591 chore(deps): Update gradle and dependencies
  .circleci/config.yml
  .travis.yml
  app/build.gradle
  app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeCheckInWork.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  versions.gradle
Labels: chore

#1550 fix: Use saveAlertDialog when back home button in action bar
  app/src/main/java/com/eventyay/organizer/core/organizer/update/UpdateOrganizerInfoFragment.java
  app/src/main/res/drawable/ic_nav_back.xml
Labels: fix

#1606 fix: Create SpeakerStatistics
  app/src/main/java/com/eventyay/organizer/data/event/EventStatistics.java
  app/src/main/java/com/eventyay/organizer/data/event/SpeakerStatistics.java
  app/src/main/res/layout/event_statistics.xml
Labels: fix

#1610 feat: Display Attendee ID on the Bottomsheet
  app/src/main/res/layout/bottomsheet_attendee_check_in.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1614 chore: Update gradle version to 3.4.0
  app/jacoco.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  versions.gradle
Labels: chore

#1618 chore: Update Appetize.io preview link
  README.md
Labels: chore
