Repository fossasia/open-event-organizer-android, pull requests merged in 2019-06, with the labels that each got.

#1680 feat: Implement system of role invites
  app/src/main/java/com/eventyay/organizer/common/di/module/ApiModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/NetworkModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/RepoModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/android/MainFragmentBuildersModule.java
  app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
  app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java
  app/src/main/java/com/eventyay/organizer/core/roleinvite/RoleInviteFragment.java
  app/src/main/java/com/eventyay/organizer/core/roleinvite/RoleInviteView.java
  app/src/main/java/com/eventyay/organizer/core/roleinvite/RoleInviteViewModel.java
  app/src/main/java/com/eventyay/organizer/data/roles/Role.java
  app/src/main/java/com/eventyay/organizer/data/roles/RoleApi.java
  app/src/main/java/com/eventyay/organizer/data/roles/RoleInvite.java
  app/src/main/java/com/eventyay/organizer/data/roles/RoleRepository.java
  app/src/main/java/com/eventyay/organizer/data/roles/RoleRepositoryImpl.java
  app/src/main/res/layout/fragment_role_invite.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/eventyay/organizer/core/event/list/EventsViewModelTest.java
Labels: feature

#1687 fix: Prevent unresponsive FAQ fragment issue
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListViewModel.java
Labels: fix

#1692 fix: Show correct state of map display checkbox
  app/src/main/res/layout/event_create_form.xml
Labels: fix

#1694 feat: Implement notifications section
  app/src/main/java/com/eventyay/organizer/common/di/module/ApiModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/ChangeListenerModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/NetworkModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/RepoModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/android/MainFragmentBuildersModule.java
  app/src/main/java/com/eventyay/organizer/core/event/list/EventListFragment.java
  app/src/main/java/com/eventyay/organizer/core/notification/list/NotificationsAdapter.java
  app/src/main/java/com/eventyay/organizer/core/notification/list/NotificationsFragment.java
  app/src/main/java/com/eventyay/organizer/core/notification/list/NotificationsView.java
  app/src/main/java/com/eventyay/organizer/core/notification/list/NotificationsViewModel.java
  app/src/main/java/com/eventyay/organizer/core/notification/list/viewholder/NotificationsViewHolder.java
  app/src/main/java/com/eventyay/organizer/data/db/configuration/OrgaDatabase.java
  app/src/main/java/com/eventyay/organizer/data/notification/Notification.java
  app/src/main/java/com/eventyay/organizer/data/notification/NotificationApi.java
  app/src/main/java/com/eventyay/organizer/data/notification/NotificationRepository.java
  app/src/main/java/com/eventyay/organizer/data/notification/NotificationRepositoryImpl.java
  app/src/main/res/layout/notification_item.xml
  app/src/main/res/layout/notifications_fragment.xml
  app/src/main/res/menu/menu_events.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1703 chore: Bump version code and name for release of v1.2.0
  app/build.gradle
Labels: chore

#1710 chore: Set minimum required Android version to 5.0
  versions.gradle
Labels: chore

#1668 chore: Move images to proper directory and update references
  README.md
  docs/images/attendees.png
  docs/images/checkin.png
  docs/images/create_ticket.png
  docs/images/dashboard_one.png
  docs/images/dashboard_two.png
  docs/images/login.png
  docs/images/navigation.png
  docs/images/order_checkin.png
  docs/images/organizer.png
  docs/images/organizer_app_branding.png
  docs/images/organizer_app_logo.png
Labels: chore

#1706 chore: Convert ScanQRPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRViewModel.java
  app/src/playStore/java/com/eventyay/organizer/core/attendee/qrscan/BarcodeDetected.java
  app/src/playStore/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRActivity.java
  app/src/playStore/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRView.java
Labels: chore

#1664 chore: Migrate ChartPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/event/chart/ChartActivity.java
  app/src/main/java/com/eventyay/organizer/core/event/chart/ChartPresenter.java
  app/src/main/java/com/eventyay/organizer/core/event/chart/ChartView.java
  app/src/main/java/com/eventyay/organizer/core/event/chart/ChartViewModel.java
Labels: chore

#1685 feat: Implement list of roles
  app/src/main/java/com/eventyay/organizer/common/di/module/ApiModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/ChangeListenerModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/NetworkModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/RepoModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/android/MainFragmentBuildersModule.java
  app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
  app/src/main/java/com/eventyay/organizer/core/role/invite/RoleInviteFragment.java
  app/src/main/java/com/eventyay/organizer/core/role/invite/RoleInviteView.java
  app/src/main/java/com/eventyay/organizer/core/role/invite/RoleInviteViewModel.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListAdapter.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListFragment.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListView.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListViewModel.java
  app/src/main/java/com/eventyay/organizer/core/role/list/viewholder/RoleViewHolder.java
  app/src/main/java/com/eventyay/organizer/data/db/configuration/OrgaDatabase.java
  app/src/main/java/com/eventyay/organizer/data/role/Role.java
  app/src/main/java/com/eventyay/organizer/data/role/RoleApi.java
  app/src/main/java/com/eventyay/organizer/data/role/RoleInvite.java
  app/src/main/java/com/eventyay/organizer/data/role/RoleRepository.java
  app/src/main/java/com/eventyay/organizer/data/role/RoleRepositoryImpl.java
  app/src/main/java/com/eventyay/organizer/data/roles/RoleApi.java
  app/src/main/java/com/eventyay/organizer/data/roles/RoleRepositoryImpl.java
  app/src/main/res/layout/fragment_role_invite.xml
  app/src/main/res/layout/role_item.xml
  app/src/main/res/layout/roles_fragment.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1708 fix: Retain 'Use picker' checkbox state on screen rotation
  app/src/main/res/layout/ends_at_time_picker.xml
  app/src/main/res/layout/event_create_form.xml
  app/src/main/res/layout/event_details_step_one.xml
  app/src/main/res/layout/session_create_form.xml
  app/src/main/res/layout/speakers_call_create_form.xml
  app/src/main/res/layout/starts_at_time_picker.xml
  app/src/main/res/layout/ticket_create_form.xml
Labels: fix

#1717 chore: Fix travis build
  .travis.yml
Labels: chore

#1718 chore: Remove option to change base URL in release build
  app/src/main/res/layout/change_password_fragment.xml
  app/src/main/res/layout/login_fragment.xml
  app/src/main/res/layout/reset_password_by_token_fragment.xml
  app/src/main/res/layout/sign_up_fragment.xml
  app/src/main/res/layout/start_fragment.xml
Labels: chore

#1661 chore: Convert AboutEventPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/event/about/AboutEventFragment.java
  app/src/main/java/com/eventyay/organizer/core/event/about/AboutEventPresenter.java
  app/src/main/java/com/eventyay/organizer/core/event/about/AboutEventViewModel.java
  app/src/test/java/com/eventyay/organizer/core/event/about/AboutEventViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/presenter/AboutEventPresenterTest.java
Labels: chore

#1699 chore: Add 'Use another URL' button for base URL
  app/src/main/java/com/eventyay/organizer/core/auth/login/LoginFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/start/StartFragment.java
  app/src/main/java/com/eventyay/organizer/core/organizer/password/ChangePasswordFragment.java
  app/src/main/res/layout/auth_url_container.xml
  app/src/main/res/values/strings.xml
Labels: chore

#1721 chore: Dismiss RoleInviteFragment after invitation is sent
  app/src/main/java/com/eventyay/organizer/core/role/invite/RoleInviteFragment.java
  app/src/main/java/com/eventyay/organizer/core/role/invite/RoleInviteViewModel.java
Labels: chore

#1725 chore: Simplify the app
  app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
  app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java
  app/src/main/res/menu/activity_main_drawer.xml
Labels: chore

#1726 fix: Prevent empty view layout from showing when items are present
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListFragment.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListFragment.java
Labels: fix

#1727 chore: Bump version code and name for release of v1.3.0
  app/build.gradle
Labels: chore

#1731 fix: Retain password visibility state on screen rotation
  app/src/main/res/layout/change_password_fragment.xml
  app/src/main/res/layout/login_fragment.xml
  app/src/main/res/layout/reset_password_by_token_fragment.xml
  app/src/main/res/layout/sign_up_fragment.xml
Labels: fix

#1735 fix: Retain state of statistics switches on screen rotation
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
  app/src/main/res/layout/event_statistics.xml
  app/src/main/res/layout/order_statistics.xml
Labels: fix

#1733 chore: Migrate AttendeesPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesPresenter.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesViewModel.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/SwipeController.java
  app/src/test/java/com/eventyay/organizer/core/presenter/AttendeePresenterTest.java
Labels: chore

#1729 chore: Set event start time as default ticket sale end time
  app/src/main/java/com/eventyay/organizer/core/ticket/create/CreateTicketViewModel.java
  app/src/test/java/com/eventyay/organizer/core/ticket/create/TicketCreateViewModelTest.java
Labels: chore

#1738 chore: Migrate CreateSessionPresenter to ViewModel
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/core/session/create/CreateSessionFragment.java
  app/src/main/java/com/eventyay/organizer/core/session/create/CreateSessionPresenter.java
  app/src/main/java/com/eventyay/organizer/core/session/create/CreateSessionViewModel.java
  app/src/test/java/com/eventyay/organizer/core/presenter/CreateSessionPresenterTest.java
  app/src/test/java/com/eventyay/organizer/core/session/create/CreateSessionViewModelTest.java
Labels: chore

#1742 chore: Remove verbose zipalign
  scripts/update-apk.sh
Labels: chore

#1744 chore: Remove debug JSON from build script
  .travis.yml
  scripts/update-apk.sh
Labels: chore

#1749 chore: Move 'My Events' to the first position in navigation drawer
  app/src/main/res/menu/activity_main_drawer.xml
Labels: chore

#1741 feat: Implement Developer Mode
  app/build.gradle
  app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
  app/src/main/java/com/eventyay/organizer/core/main/MainActivity.java
  app/src/main/java/com/eventyay/organizer/core/settings/SettingsFragment.java
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: feature

#1737 feat: Implement Places Autocomplete for location of events
  app/build.gradle
  app/src/fdroid/java/com/eventyay/organizer/core/event/create/EventDetailsStepOne.java
  app/src/fdroid/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
  app/src/fdroid/res/layout/event_create_form.xml
  app/src/fdroid/res/layout/event_details_step_one.xml
  app/src/playStore/java/com/eventyay/organizer/core/event/create/EventDetailsStepOne.java
  app/src/playStore/java/com/eventyay/organizer/core/event/create/LocationPicker.java
  app/src/playStore/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
  app/src/playStore/res/layout/event_create_form.xml
  app/src/playStore/res/layout/event_details_step_one.xml
  versions.gradle
Labels: feature

#1751 feat: Show year, start time and end time in list of events
  app/src/main/java/com/eventyay/organizer/data/event/EventDelegateImpl.java
  app/src/main/java/com/eventyay/organizer/utils/DateUtils.java
  app/src/main/res/layout/event_layout.xml
Labels: feature

#1758 chore: Remove switches for statistics from Event Dashboard
  app/src/main/res/layout/event_statistics.xml
  app/src/main/res/layout/order_statistics.xml
Labels: chore

#1756 chore: Rename 'Dashboard' to 'Event Dashboard'
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: chore

#1759 feat: Add 'My Account' in navigation drawer
  app/src/main/java/com/eventyay/organizer/core/main/DrawerNavigator.java
  app/src/main/res/drawable/ic_account.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1702 feat: Implement scanning in F-Droid build variant
  app/build.gradle
  app/src/fdroid/java/com/eventyay/organizer/common/di/module/android/FlavorModule.java
  app/src/fdroid/java/com/eventyay/organizer/core/attendee/ScanQRView.java
  app/src/fdroid/java/com/eventyay/organizer/core/attendee/ScanningDecider.java
  app/src/fdroid/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRActivity.java
  app/src/fdroid/res/layout/activity_scan_qr.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eventyay/organizer/core/attendee/qrscan/ScanQRViewModel.java
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/playStore/res/layout/activity_scan_qr.xml
Labels: feature

#1762 feat: Provide access to features via Event Dashboard
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardPresenter.java
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardView.java
  app/src/main/res/layout/fragment_event_details.xml
  app/src/test/java/com/eventyay/organizer/core/presenter/EventDashboardPresenterTest.java
Labels: feature
