Repository fossasia/open-event-organizer-android, pull requests merged in 2019-07, with the labels that each got.

#1767 chore: Update README.md according to the change in repo name
  README.md
Labels: chore

#1763 chore: Add fastlane metadata
  .gitignore
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/12.txt
  fastlane/metadata/android/en-US/changelogs/13.txt
  fastlane/metadata/android/en-US/changelogs/7.txt
  fastlane/metadata/android/en-US/changelogs/8.txt
  fastlane/metadata/android/en-US/changelogs/9.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/en-US/video.txt
  scripts/.gitignore
Labels: chore

#1768 fix: Prevent headers from shifting down in Tickets fragment
  app/src/main/java/com/eventyay/organizer/core/ticket/list/TicketsFragment.java
Labels: fix

#1766 chore: Move Payment Preferences to Edit Event
  app/src/fdroid/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
  app/src/fdroid/res/layout/event_create_form.xml
  app/src/main/java/com/eventyay/organizer/core/event/create/CreateEventActivity.java
  app/src/main/java/com/eventyay/organizer/core/settings/EventSettingsFragment.java
  app/src/main/java/com/eventyay/organizer/core/settings/PaymentPrefsFragment.java
  app/src/main/res/layout/event_create_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/event_preferences.xml
Labels: chore

#1770 chore: Simplify signing and APK generation
  .travis.yml
  app/build.gradle
  build.gradle
  scripts/prep-key.sh
  scripts/update-apk.sh
Labels: chore

#1782 chore: Update event fields
  app/src/fdroid/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
  app/src/fdroid/res/layout/event_create_form.xml
  app/src/fdroid/res/layout/event_details_step_one.xml
  app/src/main/java/com/eventyay/organizer/data/db/configuration/OrgaDatabase.java
  app/src/main/java/com/eventyay/organizer/data/event/Event.java
  app/src/main/res/layout/about_event_detail.xml
  app/src/playStore/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
  app/src/playStore/res/layout/event_create_form.xml
  app/src/playStore/res/layout/event_details_step_one.xml
Labels: chore

#1780 feat: Handle base URL in a better way
  app/src/main/java/com/eventyay/organizer/common/Constants.java
  app/src/main/java/com/eventyay/organizer/core/auth/login/LoginFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/login/LoginViewModel.java
  app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordViewModel.java
  app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/signup/SignUpViewModel.java
  app/src/main/java/com/eventyay/organizer/core/auth/start/StartFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/start/StartViewModel.java
  app/src/main/java/com/eventyay/organizer/core/organizer/password/ChangePasswordFragment.java
  app/src/main/java/com/eventyay/organizer/core/organizer/password/ChangePasswordViewModel.java
  app/src/main/res/layout/auth_url_container.xml
  app/src/test/java/com/eventyay/organizer/core/auth/reset/ResetPasswordViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/auth/signup/SignUpViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/organizer/password/ChangePasswordViewModelTest.java
Labels: feature

#1771 chore: Update APK naming convention
  scripts/update-apk.sh
Labels: chore

#1784 fix: Update list of events automatically after creation of an event
  app/src/main/java/com/eventyay/organizer/core/event/list/EventListFragment.java
Labels: fix

#1772 chore: Bump FastAdapter version and fix errors
  app/build.gradle
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/listeners/AttendeeItemCheckInEvent.java
  app/src/main/java/com/eventyay/organizer/data/attendee/Attendee.java
  app/src/main/java/com/eventyay/organizer/data/attendee/AttendeeDelegateImpl.java
Labels: chore

#1786 fix: Use correct AAB filename
  scripts/update-apk.sh
Labels: fix

#1788 fix: Prevent error in APK generation
  scripts/update-apk.sh
Labels: fix

#1792 chore: Baseline master to dev
  scripts/update-apk.sh
Labels: chore

#1791 chore: Add screenshots to fastlane
  README.md
  fastlane/metadata/android/en-US/images/checkin.png
  fastlane/metadata/android/en-US/images/create_ticket.png
  fastlane/metadata/android/en-US/images/dashboard_one.png
  fastlane/metadata/android/en-US/images/dashboard_two.png
  fastlane/metadata/android/en-US/images/login.png
  fastlane/metadata/android/en-US/images/navigation.png
  fastlane/metadata/android/en-US/images/order_checkin.png
  fastlane/metadata/android/en-US/images/organizer.png
Labels: chore

#1794 fix: Prevent Tickets fragment from becoming blank
  app/src/main/java/com/eventyay/organizer/core/ticket/list/TicketsFragment.java
Labels: fix

#1799 chore: Add 'Get it on F-Droid' badge to README.md
  README.md
Labels: chore

#1797 feat: Add app link for password reset
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eventyay/organizer/core/auth/AuthActivity.java
  app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordFragment.java
  app/src/main/java/com/eventyay/organizer/core/auth/reset/ResetPasswordViewModel.java
  app/src/main/java/com/eventyay/organizer/utils/LinkHandler.java
  app/src/test/java/com/eventyay/organizer/utils/LinkHandlerTest.java
Labels: feature

#1804 feat: Verify email with app
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailActivity.java
  app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
  app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailViewModel.java
  app/src/main/java/com/eventyay/organizer/data/auth/AuthApi.java
  app/src/main/java/com/eventyay/organizer/data/auth/AuthService.java
  app/src/main/java/com/eventyay/organizer/data/auth/AuthServiceImpl.java
  app/src/main/java/com/eventyay/organizer/data/auth/model/EmailVerificationResponse.java
  app/src/main/java/com/eventyay/organizer/data/auth/model/SubmitEmailVerificationToken.java
  app/src/main/java/com/eventyay/organizer/utils/LinkHandler.java
Labels: feature

#1807 fix: Prevent adding of duplicate items on check-in
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesViewModel.java
Labels: fix

#1808 feat: Implement sound for check-in and check-out
  app/src/main/java/com/eventyay/organizer/common/Constants.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesViewModel.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/SwipeController.java
  app/src/main/java/com/eventyay/organizer/core/settings/SettingsFragment.java
  app/src/main/res/raw/check_in_sound.wav
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: feature

#1811 chore: fix fastlane screenshot directory
  README.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/checkin.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/create_ticket.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/dashboard_one.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/dashboard_two.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/login.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/navigation.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/order_checkin.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/organizer.png
Labels: chore

#1813 feat: Implement Mapbox for event location in F-Droid build variant
  app/build.gradle
  app/src/fdroid/java/com/eventyay/organizer/core/event/create/EventDetailsStepOne.java
  app/src/fdroid/java/com/eventyay/organizer/core/event/create/LocationPicker.java
  app/src/fdroid/java/com/eventyay/organizer/core/event/create/UpdateEventFragment.java
  app/src/fdroid/res/layout/event_create_form.xml
  app/src/fdroid/res/layout/event_details_step_one.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1816 feat: Deletion of roles
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListAdapter.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListFragment.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListView.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListViewModel.java
  app/src/main/java/com/eventyay/organizer/core/role/list/viewholder/RoleViewHolder.java
  app/src/main/java/com/eventyay/organizer/data/role/RoleApi.java
  app/src/main/java/com/eventyay/organizer/data/role/RoleRepository.java
  app/src/main/java/com/eventyay/organizer/data/role/RoleRepositoryImpl.java
  app/src/main/res/layout/role_item.xml
  app/src/main/res/menu/menu_roles.xml
Labels: feature

#1818 chore: Remove double elevation in action bar and tabs in EventListFragment
  app/src/main/java/com/eventyay/organizer/core/event/list/EventListFragment.java
  app/src/main/java/com/eventyay/organizer/ui/ViewUtils.java
  app/src/main/res/layout/main_app_bar.xml
Labels: chore

#1823 chore: Update Play Services
  versions.gradle
Labels: dependencies

#1830 chore: Improve Edit Profile section
  app/src/main/java/com/eventyay/organizer/core/organizer/update/UpdateOrganizerInfoFragment.java
  app/src/main/res/layout/update_organizer_form.xml
  app/src/main/res/values/strings.xml
Labels: chore

#1829 fix: Show correct title in Edit Profile section
  app/src/main/res/layout/update_organizer_form.xml
  app/src/main/res/layout/update_organizer_layout.xml
Labels: fix

#1832 chore: Remove Suggestions from navigation drawer
  app/src/main/java/com/eventyay/organizer/core/main/DrawerNavigator.java
  app/src/main/res/menu/activity_main_drawer.xml
Labels: chore

#1835 chore: Show proper error message for 409 error code
  app/src/main/java/com/eventyay/organizer/utils/ErrorUtils.java
Labels: fix

#1839 chore: Fix travis build
  .travis.yml
Labels: chore

#1840 chore: Bump version name and code for v1.5.0
  app/build.gradle
Labels: chore

#1842 chore: Add fastlane changelog for v1.5.0
  fastlane/metadata/android/en-US/changelogs/15.txt
Labels: chore

#1837 feat: Option to delete profile picture
  app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
  app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailViewModel.java
  app/src/main/res/drawable/ic_delete_white.xml
  app/src/main/res/layout/organizer_detail_layout.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#1846 chore: Simplify event sharing process
  app/src/main/java/com/eventyay/organizer/common/di/module/ViewModelModule.java
  app/src/main/java/com/eventyay/organizer/common/di/module/android/MainFragmentBuildersModule.java
  app/src/main/java/com/eventyay/organizer/core/main/DrawerNavigator.java
  app/src/main/java/com/eventyay/organizer/core/main/FragmentNavigator.java
  app/src/main/java/com/eventyay/organizer/core/share/ShareEventFragment.java
  app/src/main/java/com/eventyay/organizer/core/share/ShareEventView.java
  app/src/main/java/com/eventyay/organizer/core/share/ShareEventViewModel.java
  app/src/main/java/com/eventyay/organizer/utils/Utils.java
Labels: chore

#1844 chore: Remove unneeded success messages
  app/src/main/java/com/eventyay/organizer/core/attendee/history/CheckInHistoryFragment.java
  app/src/main/java/com/eventyay/organizer/core/attendee/list/AttendeesFragment.java
  app/src/main/java/com/eventyay/organizer/core/event/about/AboutEventFragment.java
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
  app/src/main/java/com/eventyay/organizer/core/event/list/EventListFragment.java
  app/src/main/java/com/eventyay/organizer/core/event/list/sales/SalesSummaryViewModel.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListFragment.java
  app/src/main/java/com/eventyay/organizer/core/faq/list/FaqListViewModel.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListFragment.java
  app/src/main/java/com/eventyay/organizer/core/feedback/list/FeedbackListViewModel.java
  app/src/main/java/com/eventyay/organizer/core/notification/list/NotificationsFragment.java
  app/src/main/java/com/eventyay/organizer/core/notification/list/NotificationsViewModel.java
  app/src/main/java/com/eventyay/organizer/core/orders/create/CreateOrderFragment.java
  app/src/main/java/com/eventyay/organizer/core/orders/detail/OrderDetailFragment.java
  app/src/main/java/com/eventyay/organizer/core/orders/list/OrdersFragment.java
  app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailFragment.java
  app/src/main/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailViewModel.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListFragment.java
  app/src/main/java/com/eventyay/organizer/core/role/list/RoleListViewModel.java
  app/src/main/java/com/eventyay/organizer/core/session/list/SessionsFragment.java
  app/src/main/java/com/eventyay/organizer/core/speaker/details/SpeakerDetailsFragment.java
  app/src/main/java/com/eventyay/organizer/core/speaker/list/SpeakersFragment.java
  app/src/main/java/com/eventyay/organizer/core/speakerscall/detail/SpeakersCallFragment.java
  app/src/main/java/com/eventyay/organizer/core/sponsor/list/SponsorsFragment.java
  app/src/main/java/com/eventyay/organizer/core/ticket/list/TicketsFragment.java
  app/src/main/java/com/eventyay/organizer/core/track/list/TracksFragment.java
  app/src/main/res/values/strings.xml
  app/src/test/java/com/eventyay/organizer/core/event/sales/SalesSummaryViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/faq/list/FaqListViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/feedback/FeedbackListViewModelTest.java
  app/src/test/java/com/eventyay/organizer/core/organizer/detail/OrganizerDetailViewModelTest.java
Labels: chore

#1851 chore: Share event link and location also
  app/src/main/java/com/eventyay/organizer/core/event/about/AboutEventViewModel.java
  app/src/main/java/com/eventyay/organizer/core/event/dashboard/EventDashboardFragment.java
  app/src/main/java/com/eventyay/organizer/utils/Utils.java
Labels: chore

#1850 chore: Show end time in nav drawer and change title of account option
  app/src/main/res/layout/main_nav_header.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/values/strings.xml
Labels: chore
